### ISSUE TITLE
Have number field support negative numbers

### ISSUE THREAD

**Issue by petri** [collective/collective.tablepage#29]
Currently, the number field page template [sets a HTML5 validator pattern on the number input field](https://github.com/RedTurtle/collective.tablepage/blob/8f2daf51f718805d7ffb750e18dfac751062dcf2/collective/tablepage/fields/templates/number.pt#L17-L22). However, this pattern disallows negative numbers.

The docs do not say that the number field would only allow positive numbers. Nor does the server-side number validator say anything about number sign.

So it seems to me this is merely an oversight and the pattern should be relaxed.

**Comment by petri** [comment]
To implement this, simply add **-?** to the beginning of the regexp.

**Comment by keul** [comment]
👍
