### ISSUE TITLE
status? transfer to Plone collective?

### ISSUE THREAD

**Issue by petri** [collective/collective.tablepage#31]
Is this package going to be maintained or developed further by RedTurtle any more or is it in maintenance-for-existing-customers mode only?

Would it be ok for RedTurtle to transfer the package to the Plone collective?

I am worried that going forward, this package will otherwise stagnate and pull requests etc. to improve and enhance will not be processed in anything resembling a timely manner.

**Comment by cekk** [comment]
Hi @petri, the right answer is the second obviously ;)
I moved the repo to collective, so everyone can improve this package.

Now, if you want, you can work on your opened issues without problems.

Thanks for you help!
